# Generated by Django 4.1.7 on 2023-02-17 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('siem_solution', models.CharField(max_length=255)),
                ('firewall_solution', models.CharField(max_length=255)),
                ('av_solution', models.CharField(max_length=255)),
                ('access_control_solution', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
